-- Explore all the country our customers come from
SELECT DISTINCT Country FROM dim_customers;

-- Explore all the Categories " the Major Division"
SELECT DISTINCT Categroy, subcategory, product_Name FROM dim_products
ORDER BY 1,2,3;

-- Find the date of the First and Lasr order
SELECT MIN(Order_date) first_order_date,
MAX(Order_date) last_order_date,
round((DATEDIFF( MAX(order_date),MIN(order_date))/365),0) Order_Range_Years,
TIMESTAMPDIFF(Month, MIN(order_date), MAX(order_date)) AS Order_Range_Month
FROM fact_sales;

-- Find the youngest and oldest customer 
SELECT MIN(Birthdate) Oldest_Birthdate,
TIMESTAMPDIFF(Year, MIN(Birthdate), CURRENT_DATE()) AS Oldest_age,
MAX(Birthdate) Youngest_Birthdate,
TIMESTAMPDIFF(Year, MAX(Birthdate), CURRENT_DATE()) AS Youngest_age
FROM dim_customers;

-- ==========================================================================
-- MEASURES
-- ==========================================================================

-- Find the total sales
SELECT SUM(sales_amount) AS TotalSales FROM fact_sales;
-- Find how many items are sold
SELECT SUM(quantity) AS Total_quantity FROM fact_sales;
-- Find the average selling price
SELECT AVG(price) AS Avg_price FROM fact_sales;
-- Find the total number of orders
SELECT COUNT(order_number) AS Total_order FROM fact_sales;
SELECT COUNT(DISTINCT order_number) AS Total_order FROM fact_sales;
-- Find the total number of products
SELECT COUNT(product_key) AS Total_product FROM dim_products;
-- Find the total number of customers
SELECT COUNT(customer_key) AS Total_customers FROM dim_customers;
-- Find the total number of customers that has placed an order 
SELECT COUNT(DISTINCT customer_key) AS Total_customers FROM fact_sales;

-- ====================================================================
-- Generate a report that show all key matrix of the Business
-- ====================================================================
SELECT 'Total Sales' AS Measure_Name, SUM(sales_amount) AS Measure_Value FROM fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM fact_sales
UNION ALL 
SELECT 'Avarage Price', AVG(price) FROM fact_sales
UNION ALL
SELECT 'Total Nr. Order', COUNT(order_number)   FROM fact_sales
UNION ALL
SELECT 'Total Nr.Product', COUNT(product_key) FROM dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key)  FROM dim_customers
UNION ALL
SELECT 'Total Customers', COUNT(DISTINCT customer_key) FROM fact_sales;

-- ====================================================================
-- Magnetic Analysis: Compare the measure values by categories.
-- It help us understand the importance of different categories. 
-- ====================================================================

-- Find total customer by the countries
SELECT Country,
COUNT(customer_key) AS Total_Customer
FROM dim_customers
GROUP BY Country
ORDER BY Total_customer DESC;

-- Find total customers by gender
SELECT Gender,
COUNT(customer_key) AS Total_Customer
FROM dim_customers
GROUP BY Gender
ORDER BY Total_customer DESC;

-- Find total product by category
SELECT Categroy,
COUNT(Product_Key) AS Total_product
FROM dim_products
GROUP BY Categroy
ORDER BY Total_product DESC;

-- What is the average costs in each category?
SELECT Categroy,
ROUND(Avg(cost),0) AS Avg_Cost
FROM dim_products
GROUP BY Categroy
ORDER BY Avg_Cost DESC;
-- What is the total revenue generated for each category?
SELECT p. categroy,
SUM(sales_amount) Total_Revenue
FROM fact_sales f
LEFT JOIN dim_products p  
ON f.product_Key = p.product_key
GROUP BY Categroy
ORDER BY Total_Revenue DESC;

-- Find total revenue is generated by each customer 
SELECT 
customer_Id,
First_Name,
Last_Name,
SUM(Sales_amount) Total_Revenue
FROM fact_sales f
LEFT JOIN dim_customers c
ON f.customer_Key = c.customer_Key
GROUP BY customer_Id,
First_Name,
Last_Name
ORDER BY Total_Revenue DESC;

-- What is the distribution of sold items across countries?
SELECT 
country,
SUM(quantity) Total_Quantity
FROM fact_sales f
LEFT JOIN dim_customers c
ON f.customer_Key = c.customer_Key
GROUP BY country
ORDER BY Total_Quantity DESC;

-- ====================================================================
-- Ranking Analysis: Order the value of Dimensions by measure.
-- Top N Performers | Bottom N Performers 
-- ====================================================================

-- Which 5 products generate the Highest revenue?
SELECT p. product_Name,
SUM(sales_amount) Total_Revenue
FROM fact_sales f
LEFT JOIN dim_products p  
ON f.product_Key = p.product_key
GROUP BY product_Name
ORDER BY Total_Revenue DESC
Limit 5;

-- 2ND METHOD (USING WINDOW FUNCTION)

SELECT * FROM (
SELECT p. product_Name,
SUM(sales_amount) Total_Revenue,
ROW_NUMBER() OVER(ORDER BY SUM(sales_amount) DESC) AS Row_Num
FROM fact_sales f
LEFT JOIN dim_products p  
ON f.product_Key = p.product_key
GROUP BY product_Name)t
WHERE Row_Num <= 5;

-- what are the 5 worst-performing products in terms of sales?
SELECT p. product_Name,
SUM(sales_amount) Total_Revenue
FROM fact_sales f
LEFT JOIN dim_products p  
ON f.product_Key = p.product_key
GROUP BY product_Name
ORDER BY Total_Revenue ASC
Limit 5;


-- Find the top 10 customers who have generated the highest revenue 
SELECT 
customer_Id,
First_Name,
Last_Name,
SUM(Sales_amount) Total_Revenue,
ROW_NUMBER() OVER(ORDER BY SUM(Sales_amount) DESC) Highest_Revenue
FROM fact_sales f
LEFT JOIN dim_customers c
ON f.customer_Key = c.customer_Key
GROUP BY customer_Id,
First_Name,
Last_Name
ORDER BY Total_Revenue DESC
LIMIT 10;

-- 3 customers with fewest orders placed

SELECT 
C.customer_KEY,
First_Name,
Last_Name,
Count(DISTINCT Order_number) Total_ORDER,
ROW_NUMBER() OVER(ORDER BY COUNT(DISTINCT Order_number) ASC) Lowest_order_customers
FROM fact_sales f
LEFT JOIN dim_customers c
ON f.customer_KEY = c.customer_KEY
GROUP BY C.customer_KEY,
First_Name,
Last_Name

LIMIT 3;

-- 2ND METHOD

SELECT 
C.customer_KEY,
First_Name,
Last_Name,
Count(DISTINCT Order_number) Total_ORDERS
FROM fact_sales f
LEFT JOIN dim_customers c
ON f.customer_KEY = c.customer_KEY
GROUP BY C.customer_KEY,
First_Name,
Last_Name
ORDER BY Total_ORDERS
LIMIT 20;
